// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NTLLab6_EF.Entities;

#nullable disable

namespace NTLLab6_EF.Migrations
{
    [DbContext(typeof(NTLAppDbContext))]
    partial class NTLAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NTLLab6_EF.Models.NTLCategory", b =>
                {
                    b.Property<int>("NTLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NTLId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NTLName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NTLId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("NTLLab6_EF.Models.NTLProduct", b =>
                {
                    b.Property<int>("NTLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NTLId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NTLCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("NTLDescriptions")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("ntext");

                    b.Property<string>("NTLImage")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NTLName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("NTLPrice")
                        .HasColumnType("real");

                    b.Property<float>("NTLSalePrice")
                        .HasColumnType("real");

                    b.Property<byte>("NTLStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("NTLId");

                    b.HasIndex("NTLCategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("NTLLab6_EF.Models.NTLProduct", b =>
                {
                    b.HasOne("NTLLab6_EF.Models.NTLCategory", "nTLCategory")
                        .WithMany("NTLProducts")
                        .HasForeignKey("NTLCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nTLCategory");
                });

            modelBuilder.Entity("NTLLab6_EF.Models.NTLCategory", b =>
                {
                    b.Navigation("NTLProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
